### ISSUE TITLE
New error with version 1.3.0

### ISSUE THREAD

**Issue by ntowle** [spromicky/Details_Covenants#10]
Message: Interface\AddOns\Details_Covenants\Core.lua:35: Usage: GetPlayerInfoByGUID("playerGUID")
Time: Wed Nov  3 21:07:35 2021
Count: 20
Stack: Interface\AddOns\Details_Covenants\Core.lua:35: Usage: GetPlayerInfoByGUID("playerGUID")
[string "=[C]"]: in function `GetPlayerInfoByGUID'
[string "@Interface\AddOns\Details_Covenants\Core.lua"]:35: in function <Interface\AddOns\Details_Covenants\Core.lua:30>

Locals: (*temporary) = ""

**Comment by spromicky** [comment]
Fixed in version `1.3.1`. But I don't have an opportunity to check it in game. Can you help me with that and give me some response about fixing this issue?

**Comment by ntowle** [comment]
Seems to be fixed, thanks @spromicky.
