### ISSUE TITLE
Disable chat covenant detection account wide

### ISSUE THREAD

**Issue by zeenk** [spromicky/Details_Covenants#13]
Hello again, I know I asked about this before but on Curseforge and you told me to edit this part

![2022-05-23_22-22-51](https://user-images.githubusercontent.com/68170439/169900082-c3d2a05f-4ee0-44e8-b21c-ef148518e927.png)

I recently reinstalled the addon and removed line 74 like I did last time I asked about this (and it worked back then) but for some reason it's not working anymore, still printing the detection in chat :/ I know I can do /dc chat off but a bit annoying to do that on 100+ characters.
My edit: 
![2022-05-23_22-21-50](https://user-images.githubusercontent.com/68170439/169900330-8f476bd3-5887-4cb6-ae46-5471b6883625.png)

[Oribos.zip](https://github.com/spromicky/Details_Covenants/files/8757881/Oribos.zip) Did I do something wrong this time? 🤔 

Thanks.

**Comment by spromicky** [comment]
Hi, yep, the code was updated, and the link on that line is not valid anymore. For now, the number of line, that you are looking for is [81](https://github.com/spromicky/Details_Covenants/blob/master/Oribos.lua#L81).

**Comment by zeenk** [comment]
Thank you! that fixed it :)
