### ISSUE TITLE
Conflict 

### ISSUE THREAD

**Issue by gaveer** [spromicky/Details_Covenants#14]
@spromicky 
i have issue with addon conflict with another addon has the same commands ,
default Profile has chat on  `/dc chat [on | off]` 
when i ever enter a dungeon i keep getting : you are not in a party , and the covanant chat not working . 
The addon that has the same commands is : [DynamicCam](https://www.curseforge.com/wow/addons/dynamiccam)

 can we do something about this ?

**Comment by spromicky** [comment]
Hi, sure. You can use `/dcovenants chat [on|off]` instead.

**Comment by gaveer** [comment]
becouse the other addon has the same cmd it wont **print** on the chat 
- character's covenant to chat
and keep give ` You are not in party ` in the chat

**Comment by spromicky** [comment]
Can not check this, but you can disable `DynamicCam` addon, then turn off printing in chat for `Details_Covenants`. And after that enable `DynamicCam`.

**Comment by gaveer** [comment]
i did that but problem still **persists**

**Comment by gaveer** [comment]
if i turn `DynamicCam` off no massege apper

**Comment by spromicky** [comment]
Conflict in commands make can't be a reason for this message. Only that one addon will respond for a command `/dc` that's all. 

And if you disable `DynamicCam` and the message is gone maybe `DynamicCam` is the reason for the problem?

**Comment by gaveer** [comment]
i report this issue on both addon , if you think this from `DynamicCam` i close ticket
