### ISSUE TITLE
Switch to Details OpenRaidLib

### ISSUE THREAD

**Issue by yoshimo** [spromicky/Details_Covenants#15]
https://github.com/Tercioo/Open-Raid-Library/blob/67a116de56204373f395a94a4a0ffed45f0fbc5d/GetPlayerInformation.lua
has this data and is packaged alongside Details.
You can remove your own version of the CovenantData sync via SendAddonMessage.

**Comment by spromicky** [comment]
Thanks, but covenants are gone (thanks, N`Zoth), and this addon is no more supported.
