### ISSUE TITLE
Figure out covenants by using 'GetCovenantId'

### ISSUE THREAD

**Issue by IvanDeluxe** [spromicky/Details_Covenants#5]
Hey :)

There's this addon: https://www.curseforge.com/wow/addons/whats-your-covenant

It keeps an updated database of players' covenants and exposes a method: 'GetCovenantId'

```
GetCovenantId

Arguments
realm - the realm name of the player (e.g. "Twisting Nether")
player - the name of the player (e.g. "Deathbetray")

Returns
id - the covenant ID of the given player
timestamp - the UNIX time (in seconds) the player's covenant was last acquired (personal database uses GetServerTime())
fromPersonalDb - true if the data was found in the personal database (rather than the data packaged with the addon)

All return values are nil if the player isn't found
```

It would be awesome if you could implement it .. maybe something like this:

If user has 'What's Your Covenant' installed & 'GetCovenantId' returns data for player: use 'GetCovenantId' to determine player's covenant;

otherwise fallback to the current system and figure out the covenant based on skills :)

Amazing work btw! ^^

**Comment by spromicky** [comment]
Hi, I checked out it. Database of addon is depends on how frequently it will be updated. Otherwise it used the same mechanisms as this addon do, but not so effectively and, have less spell ids to check. I'll watch how frequently it will be updated and added it in next versions. Thx for advice.

**Comment by spromicky** [comment]
Since players can freely change covenant in any time, I think this integration not relevant any more.
